name: Node.js CI

on:
  push:
    paths-ignore:
    - 'README.MD'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    strategy:
      matrix:
        node-version: [14.x]
    env:
      UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
